from pathlib import Path
import math

MARKET_CONFIG = {
    "player_pass_yds": {
        "label": "Passing Yards",
        "display_name": "PASS YARDS",
        "bookmaker": "fanduel",
        "actual_col": "passing_yards",
        "actual_col_candidates": [
            "actual_passing_yards",
            "actual_pass_yds",
            "passing_yards",
            "pass_yds",
        ],
        "stat_col_candidates": [
            "passing_yards",
            "pass_yds",
        ],
        "projection_col": "weighted_projection",
        "distribution": "normal",
        "primary_actuals_file": Path("data/processed/pff/pff_passing_weekly.csv"),
        "fallback_actuals_file": Path("data/processed/pff/pff_player_weekly_master.csv"),
        "history_file": Path("data/processed/fanduel_pass_yds_history.csv"),
        "input_file": "data/processed/fanduel_pass_yds_history.csv",
        "analysis_rows_file": Path("data/analysis/pass_yds_market_analysis_rows.csv"),
        "output_slug": "pass_yds",
        "positions": ["QB"],
        "line_bins": [-math.inf, 180, 220, 260, 300, math.inf],
        "line_labels": ["<180", "180-220", "220-260", "260-300", "300+"],
        "max_actual": 600,
        "default_clean_filter": {
            "min_attempt_col": "pass_attempts",
            "min_attempts": 10,
            "min_actual": 25,
            "residual_min": -200,
            "residual_max": 200,
        },
        "known_sigma": 68.488252,
        "min_line": 0,
        "line_col": "line",
        "projection_engine": {
            "reference_engine": "passing_ensemble",
            "projections_file": Path("data/input/week_pass_yds_projections.csv"),
            "output_file": Path("data/analysis/week_pass_yds_ensemble_bets.csv"),
            "line_col": "market_line",
            "odds_format": "decimal",
            "outcome_sigma": 68.488252,
            "source_sigma": {
                "fantasypros": 18,
                "pff": 14,
                "fantasy_points": 14,
                "etr": 12,
                "your_model": 16,
            },
            "recommendation_thresholds": {
                "strong_bet_elite_edge": 15,
                "bet_edge": 10,
                "lean_edge": 5,
            },
            # The reference passing ensemble has no minimum-line or simulation CLI filter.
            "passes_min_line": False,
        },
        "backtest": {
            "reference_engine": "simulate_pass_yds",
            "picks_file": Path("data/historical_props/pass_yds_baseline_predictions.csv"),
            "output_file": Path("data/historical_props/pass_yds_sim_results.csv"),
            "output_dir": Path("data/historical_props"),
            "odds_format": "american",
            "n_sims": 10_000,
            "random_seed": 42,
            "candidate_probability": 0.55,
        },
    },

    "player_receptions": {
        "label": "Receptions",
        "display_name": "RECEPTIONS",
        "bookmaker": "fanduel",
        "actual_col": "receptions",
        "actual_col_candidates": [
            "actual_receptions",
            "receptions",
        ],
        "stat_col_candidates": [
            "receptions",
        ],
        "projection_col": "projected_receptions",
        "distribution": "negative_binomial",
        "primary_actuals_file": Path("data/processed/pff/pff_player_weekly_master.csv"),
        "fallback_actuals_file": None,
        "history_file": Path("data/processed/fanduel_receptions_history.csv"),
        "input_file": "data/processed/fanduel_receptions_history.csv",
        "analysis_rows_file": Path("data/analysis/receptions_market_analysis_rows.csv"),
        "output_slug": "receptions",
        "positions": ["WR", "TE", "HB", "FB", "RB"],
        "line_bins": [0, 2.5, 3.5, 4.5, 5.5, 6.5, math.inf],
        "line_labels": ["<=2.5", "3.5", "4.5", "5.5", "6.5", "7+"],
        "max_actual": 50,
        "default_clean_filter": {
            "min_actual": 0,
            "residual_min": -10,
            "residual_max": 10,
        },
        "known_sigma": None,
        "min_line": 1.5,
        "line_col": "line",
        "projection_engine": {
            "projections_file": Path("data/processed/fantasypros_weekly_projections_api.csv"),
            "markets_file": Path("data/processed/fanduel_receptions_history.csv"),
            "history_file": Path("data/analysis/receptions_market_analysis_rows.csv"),
            "output_file": Path("data/analysis/receptions_model_bets.csv"),
            "projection_col_fallback_candidates": [
                "fp_receptions",
                "projection",
                "weighted_projection",
                "ensemble_projection",
                "fantasy_projection",
                "receptions_projection",
                "rec_projection",
                "receptions",
            ],
            "n_sims": 20_000,
            "random_seed": 42,
            "min_ev": 0.02,
            "min_prob": 0.525,
            "max_sim_value": 25,
            # The legacy receptions engine has no minimum-line filter.
            "passes_min_line": False,
        },
        "backtest": {
            "picks_file": Path("data/analysis/receptions_model_bets.csv"),
            "history_file": Path("data/analysis/receptions_market_analysis_rows.csv"),
            "output_dir": Path("data/analysis/backtests"),
            "merge_keys": ["season", "week", "player_norm", "line"],
            "required_pick_keys": ["season", "week", "player_norm", "line"],
            "blocked_reason": (
                "The parity-preserving receptions projection output omits season/week. "
                "A player_norm/line merge is many-to-many across historical games, "
                "so valid receptions ROI requires a separate backtest-safe picks output."
            ),
            "odds_format": "decimal",
            "side_filter": None,
            "min_ev_percent": 2,
            "max_ev_percent": 10,
            "filter_message": "EV 2-10",
            "edge_col": "edge_receptions",
            "summary_edge_col": "avg_edge_receptions",
            "edge_bins": [0, 0.5, 1, 1.5, 2, 3, 4, 999],
            "edge_labels": ["0-0.5", "0.5-1", "1-1.5", "1.5-2", "2-3", "3-4", "4+"],
            "ev_bins": [-999, 0, 2, 5, 10, 15, 20, 999],
            "ev_labels": ["<0", "0-2", "2-5", "5-10", "10-15", "15-20", "20+"],
            "summary_heading": "RECEPTIONS SUMMARY",
        },
        "context_flags": {
            "watch_wr_underdog_high_total": True,
            "high_total_cutoff": 47,
        },
    },

    "player_reception_yds": {
        "label": "Receiving Yards",
        "display_name": "RECEIVING YARDS",
        "bookmaker": "fanduel",
        "actual_col": "receiving_yards",
        "actual_col_candidates": [
            "actual_receiving_yards",
            "actual_reception_yards",
            "receiving_yards",
            "reception_yards",
            "rec_yds",
        ],
        "stat_col_candidates": [
            "receiving_yards",
            "reception_yards",
            "rec_yds",
        ],
        "projection_col": "fp_receiving_yds",
        "distribution": "normal",
        "primary_actuals_file": Path("data/processed/pff/pff_player_weekly_master.csv"),
        "fallback_actuals_file": None,
        "history_file": Path("data/historical_props/merged_props_with_context.csv"),
        "input_file": "data/historical_props/merged_props_with_context.csv",
        "analysis_rows_file": Path("data/analysis/reception_yds_market_analysis_rows.csv"),
        "output_slug": "reception_yds",
        "positions": ["WR", "TE", "HB", "FB", "RB"],
        "line_bins": [-math.inf, 20, 30, 40, 50, 60, 75, math.inf],
        "line_labels": ["<20", "20-30", "30-40", "40-50", "50-60", "60-75", "75+"],
        "max_actual": 250,
        "default_clean_filter": {
            "min_actual": 0,
            "residual_min": -100,
            "residual_max": 150,
        },
        "known_sigma": None,
        "min_line": 15,
        "line_col": "line",
        "recommendation_filters": {
            "exclude_high_line_favorite_wr_overs": True,
            "favorite_wr_over_min_line": 50,
        },
        "projection_engine": {
            "projections_file": Path("data/processed/fantasypros_weekly_projections_api.csv"),
            "markets_file": Path("data/historical_props/merged_props_with_context.csv"),
            "history_file": Path("data/analysis/reception_yds_market_analysis_rows.csv"),
            "output_file": Path("data/analysis/reception_yds_model_bets.csv"),
            "projection_col_fallback_candidates": [
                "projected_receiving_yards",
                "projected_reception_yds",
                "projected_reception_yards",
                "projection",
                "weighted_projection",
                "ensemble_projection",
                "fantasy_projection",
                "receiving_yards_projection",
                "receiving_yards",
            ],
            "line_bins": [0, 20, 30, 40, 50, 60, math.inf],
            "line_labels": ["<20", "20-30", "30-40", "40-50", "50-60", "60+"],
            "std_inflation_factor": 1.15,
            "n_sims": 20_000,
            "random_seed": 42,
            "min_ev": 0.02,
            "min_prob": 0.525,
            "max_sim_value": 350,
        },
        "backtest": {
            "picks_file": Path("data/analysis/test_reception_yds_model_bets_api.csv"),
            "history_file": Path("data/analysis/reception_yds_market_analysis_rows.csv"),
            "output_dir": Path("data/analysis/backtests"),
            "odds_format": "american",
            "side_filter": None,
            "min_ev_percent": 2,
            "max_ev_percent": 10,
            "filter_message": "EV 2-10",
            "edge_bins": [0, 2.5, 5, 7.5, 10, 15, 20, 999],
            "edge_labels": ["0-2.5", "2.5-5", "5-7.5", "7.5-10", "10-15", "15-20", "20+"],
            "ev_bins": [-999, 0, 2, 5, 10, 15, 20, 999],
            "ev_labels": ["<0", "0-2", "2-5", "5-10", "10-15", "15-20", "20+"],
        },
    },

    "player_rush_yds": {
        "label": "Rushing Yards",
        "display_name": "RUSHING YARDS",
        "bookmaker": "fanduel",
        "actual_col": "rushing_yards",
        "actual_col_candidates": [
            "actual_rushing_yards",
            "actual_rush_yds",
            "rushing_yards",
            "rush_yds",
            "rush_yards",
        ],
        "stat_col_candidates": [
            "rushing_yards",
            "rush_yds",
            "rush_yards",
        ],
        "projection_col": "fp_rush_yds",
        "distribution": "normal",
        "primary_actuals_file": Path("data/processed/pff/pff_player_weekly_master.csv"),
        "fallback_actuals_file": None,
        "history_file": Path("data/historical_props/merged_props_with_context.csv"),
        "input_file": "data/historical_props/merged_props_with_context.csv",
        "analysis_rows_file": Path("data/analysis/rush_yds_market_analysis_rows.csv"),
        "output_slug": "rush_yds",
        "positions": ["QB", "HB", "FB", "RB"],
        "line_bins": [-math.inf, 20, 40, 60, 80, math.inf],
        "line_labels": ["<20", "20-40", "40-60", "60-80", "80+"],
        "max_actual": 250,
        "default_clean_filter": {
            "min_actual": 0,
            "residual_min": -100,
            "residual_max": 150,
        },
        "known_sigma": None,
        "min_line": 5,
        "line_col": "line",
        "projection_engine": {
            "projections_file": Path("data/processed/fantasypros_weekly_projections_api.csv"),
            "markets_file": Path("data/historical_props/merged_props_with_context.csv"),
            "history_file": Path("data/analysis/rush_yds_market_analysis_rows.csv"),
            "output_file": Path("data/analysis/rush_yds_model_bets.csv"),
            "projection_col_fallback_candidates": [
                "projected_rush_yds",
                "projected_rushing_yards",
                "rushing_yards_projection",
                "rushing_yards",
                "projection",
                "weighted_projection",
                "ensemble_projection",
                "fantasy_projection",
            ],
            "std_inflation_factor": 1.25,
            "n_sims": 20_000,
            "random_seed": 42,
            "min_ev": 0.02,
            "min_prob": 0.525,
            "max_sim_value": 350,
        },
        "backtest": {
            "picks_file": Path("data/analysis/rush_yds_model_bets.csv"),
            "history_file": Path("data/analysis/rush_yds_market_analysis_rows.csv"),
            "output_dir": Path("data/analysis/backtests"),
            "odds_format": "american",
            "side_filter": "under",
            "min_ev_percent": 0,
            "max_ev_percent": 15,
            "filter_message": "unders only, EV 0-15",
            "edge_bins": [0, 2.5, 5, 7.5, 10, 15, 20, 999],
            "edge_labels": ["0-2.5", "2.5-5", "5-7.5", "7.5-10", "10-15", "15-20", "20+"],
            "ev_bins": [-999, 0, 2, 5, 10, 15, 20, 999],
            "ev_labels": ["<0", "0-2", "2-5", "5-10", "10-15", "15-20", "20+"],
            "summary_heading": "RUSH YARDS SUMMARY",
            "print_side_recommendations": True,
        },
    },
}



def get_market_config(market_key: str) -> dict:
    if market_key not in MARKET_CONFIG:
        valid = ", ".join(sorted(MARKET_CONFIG))
        raise KeyError(f"Unknown market_key={market_key}. Valid options: {valid}")

    return MARKET_CONFIG[market_key]
